title: My-Note
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This document is about what I'm interested in and what I'm learning. 
  Since I am especially interested in computer science, I often write articles on those topics. 
  I write articles either in Japanese or English. 
  Basically, I will be writing mostly in Japanese, but I would like to challenge myself to write in English as well.
baseurl: /my-note/docs # the subpath of your site, e.g. /blog
domain: sfurukawa7.github.io
url: https://sfurukawa7.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  sfurukawa7

# Build settings
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme